CarsStore/Controllers/CarController.cs
using CarsStore.ViewModel.BaseViewModel;
using CarsStore.ViewModel.CarViewModel;
using CarStoreDbEF.Entities;
using CarStoreDbEF.Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CarsStore.Controllers
{
    public class CarController : BaseController<Car,
                                               CarRepository,
                                               CarDeleteViewModel,
                                               CarEditViewModel,
                                               CarListViewModel>
    {
        public override CarDeleteViewModel GetMapperDelete(Car entity)
        {
            CarDeleteViewModel model = new CarDeleteViewModel();

            model.Id = entity.Id;
            model.Brand = entity.Brand;
            model.Model = entity.Model;
            model.ManafDate = entity.ManafDate;
            model.Price = entity.Price;
            model.ImgLink = entity.ImgLink;

            return model;
        }

        public override CarEditViewModel GetMapperEdit(Car entity)
        {

            CarEditViewModel model = new CarEditViewModel();

            model.Id = entity.Id;
            model.Brand = entity.Brand;
            model.Model = entity.Model;
            model.ManafDate = entity.ManafDate;
            model.Price = entity.Price;
            model.ImgLink = entity.ImgLink;

            return model;
        }


        public override Car PostMapperEdit(CarEditViewModel model)
        {
            Car entity = new Car();

            entity.Id = model.Id;
            entity.Brand = model.Brand;
            entity.Model = model.Model;
            entity.ManafDate = model.ManafDate;
            entity.Price = model.Price;
            entity.ImgLink = model.ImgLink;

            return entity;
        }

        public override ActionResult Index(int page = 1)
        {
            User user = new User();
            user = (User)Session["LoggedUser"];

            if (user == null)
                return RedirectToAction("Login", "Home");

            CarRepository repository = new CarRepository();
            CarListViewModel listviewmodel = new CarListViewModel();

            listviewmodel.items = repository.GetAll();
            listviewmodel.IsAdmin = user.IsAdmin;

            int pageSize = 3;// количество объектов на страницу
            IEnumerable<Car> objectsPerPage = listviewmodel.items.Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = listviewmodel.items.Count };

            CarListViewModel ivm = new CarListViewModel { PageInfo = pageInfo, items = objectsPerPage.ToList<Car>() };
            ivm.IsAdmin = user.IsAdmin;

            return View(ivm);


            //return View(listviewmodel);
        }
        


        public ActionResult StartPage()

        {
            CarRepository repository = new CarRepository();
            CarListViewModel model = new CarListViewModel();

            User user = (User)Session["LoggedUser"];

            if (user == null)
                return RedirectToAction("Login", "Home");

            string connectionString = ConfigurationManager.ConnectionStrings["CarStoreDb"].ToString();


            model.items = repository.GetTopCars(connectionString);        
            model.IsAdmin = user.IsAdmin;

            return View(model);
        }

    }
}

CarsStore/Controllers/OrderController.cs
using CarsStore.ViewModel.BaseViewModel;
using CarsStore.ViewModel.OrderViewModel;
using CarStoreDbEF.Entities;
using CarStoreDbEF.Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CarsStore.Controllers
{
    public class OrderController : Controller
    {
        public ActionResult Index(int page= 1)
        {
            User user = new User();
            user = (User)Session["LoggedUser"];

            if (user == null)
                return RedirectToAction("Login", "Home");

            string connectionString = ConfigurationManager.ConnectionStrings["CarStoreDb"].ToString();

            OrderRepository orderRepository = new OrderRepository();
            OrderListViewModel orderListViewModel = new OrderListViewModel();

            orderListViewModel.items = orderRepository.getOrderData(connectionString);

            int pageSize = 10; // количество объектов на страницу
            IEnumerable<OrderData> objectsPerPage = orderListViewModel.items.Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = orderListViewModel.items.Count };
            OrderListViewModel ivm = new OrderListViewModel { PageInfo = pageInfo, items = objectsPerPage.ToList<OrderData>() };
            ivm.IsAdmin = user.IsAdmin;

            return View(ivm);
        }

        [HttpGet]
        public ActionResult Purchase(int id)
        {
            PurchaseViewModel model = new PurchaseViewModel();
            User user = (User)Session["LoggedUser"];

            CarRepository carRepository = new CarRepository();

            Car car = carRepository.GetById(id);


            model.UserId = user.Id;
            model.CarId = car.Id;
            model.Brand = car.Brand;
            model.Model = car.Model;
            model.Price = car.Price;


            return View(model);
        }
        [HttpPost]
        public ActionResult Purchase(PurchaseViewModel model)
        {
            Order order = new Order();
            OrderRepository orderRepository = new OrderRepository();

            order.CarId = model.CarId;
            order.UserId = model.UserId;
            order.OrderDate = DateTime.Now;
            order.Warranty = model.Warranty;


            orderRepository.Save(order);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            OrderRepository repository = new OrderRepository();
            Order order = repository.GetById(id);
            OrderDeleteViewModel model = new OrderDeleteViewModel();

            model.Id = order.Id;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(OrderDeleteViewModel model)
        {
            OrderRepository repository = new OrderRepository();

            repository.Delete(model.Id);

            return RedirectToAction("Index");
        }






    }
}

CarsStore/Views/Car/Delete.cshtml
@model CarsStore.ViewModel.CarViewModel.CarDeleteViewModel
@{
    ViewBag.Title = "Delete";
}
<h2>Delete Car</h2>
@if (Session["LoggedUser"] != null)
{
<h3>@Session["UserName"], are you sure you want to delete this car??</h3>
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManafDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManafDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgLink)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarsStore/Views/Car/Edit.cshtml
@model CarsStore.ViewModel.CarViewModel.CarEditViewModel
@{
    ViewBag.Title = Model.Id > 0 ? "Edit" : "Add";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Car", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Brand, new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Brand, new { @class = "control-label col-md-10" })
            @Html.ValidationMessageFor(model => model.Brand)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Model, new { @class = "control-label col-md-10" })
            @Html.ValidationMessageFor(model => model.Model)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManafDate, new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.ManafDate, new { @class = "control-label col-md-10" })
            @Html.ValidationMessageFor(model => model.ManafDate)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Price, new { @class = "control-label col-md-10" })
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImgLink, new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.ImgLink, new { @class = "control-label col-md-10" })
            @Html.ValidationMessageFor(model => model.ImgLink)
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CarsStore/Views/Car/Index.cshtml
@model CarsStore.ViewModel.CarViewModel.CarListViewModel
@using CarsStore.Helpers
@{
    ViewBag.Title = "Index";
}

<h2>Car Page</h2>
@if (Model.IsAdmin)
{
    @Html.ActionLink("Add new", "Edit", "Car")
}


<table class="table">
    <thead>
        <tr>
            <th>Brand</th>
            <th>Model</th>
            <th>ManafDate</th>
            <th>Price</th>
            <th>Photo</th>
            @if (Model.IsAdmin)
            {
                <th>Actions</th>
            }
            @if (!Model.IsAdmin)
            {
                <th>Action</th>

            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.items)
        {
            <tr>
                <td>@item.Brand</td>
                <td>@item.Model</td>
                <td>@item.ManafDate</td>
                <td>@item.Price</td>
                <td><img src="@item.ImgLink" alt="Photo of the car" width="350" height="200"></td>
                @if (Model.IsAdmin)
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Car", new { id = item.Id }, null) 
                        |
                        @Html.ActionLink("Delete", "Delete", "Car", new { id = item.Id }, null)
                    </td>
                }
                @if (!Model.IsAdmin)
                {
                    <td> @Html.ActionLink("Buy", "Purchase", "Order", new { id = item.Id }, null)</td>
                }
            </tr>
        }
    </tbody>
</table>
<div class="btn-group">
    @Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x }))
</div>

CarsStore/Views/Car/StartPage.cshtml
@model CarsStore.ViewModel.CarViewModel.CarListViewModel
@{
    ViewBag.Title = "Start Page ";

}

<h1>The biggest car store in the world!</h1>

<table class="table1">
    <thead>
        <tr>
            <th>Brand</th>
            <th>Model</th>
            <th>Price</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.items)
        {
            <tr>
                <td>@item.Brand</td>
                <td>@item.Model</td>
                <td>@item.Price</td>
            </tr>
        }
    </tbody>
</table>

<table class="table2">
    Why should you buy in The CarStore?
    <p>
        Because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
        because because because because because because because because because because
    </p>
    <p>Also, to have good knowledges in ASP.NET you should regularly attend the lectures of Nikola Valchanov</p>
    <p>Be Happy!</p>
    <p>Piece</p>

</table>